### PR TITLE
Added DLC for a lot of Paradox games

### PR DESCRIPTION
**Pull request by pipoliviero**
Added all DLC for Imperator: Rome, Crusader Kings III, Surviving Mars, Surviving the Aftermath, Age of Wonders: Planetfall, Golf With Your Friends

### CODE REVIEW

**Comment by pipoliviero** [comment]
Not exactly sure how github works yet so bear with me here :3

**Comment by 20PercentRendered** [comment]
Is this ready to merge?

**Comment by 20PercentRendered** [comment]
@pipoliviero Would like to get this merged if it's ready. Is this PR complete or are you planning to add more into the list?

**Comment by pipoliviero** [comment]
To the best of my understanding it is complete and functional. It adds every dlc from every paradox game that has been slightly relevant in the past couple years and I shouldn't have to add much more other than the occasional new dlc.

**Pull request merged**
